# chicken coop door. Based on 'cover' template of ESPHome.
# see https://esphome.io/components/cover/template.html

# 'endstop cover' (https://esphome.io/components/cover/endstop.html?highlight=endstop%20cover)
# is another candidate

# connections
# outputs = [('d1',5),('d2',4)]
# inputs = [('d0',16),('d5',14)]

# switches:

# d0 - upper switch
# d5 - lower switch
# closed: both 0
# open: d5=1, d0=1

# DHT sensor
# pin 13
#
# old python code:
#
# sensor = dht.DHT22(machine.Pin(pin))
# sensor = Sensor(13)

esphome:
  name: coop_door
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# sunrise automation
sun:
  latitude: !secret latitude
  longitude: !secret longitude

  #   on_sunrise:
  #     - then:
  #         - logger.log: "Sunrise! ...will open after 10 min"
  #         - delay: 10min
  #         - cover.open: coop_door
  on_sunset:
    - then:
        - logger.log: "Sunset! ...will close after 25 min"
        - delay: 25min
        - if:
            condition:
              binary_sensor.is_on: door_open_sensor
            then:
              - logger.log: "Closing door."
              - cover.close: coop_door
            else:
              - logger.log: "Door is already closed."

text_sensor:
  - platform: sun
    name: Next Sunrise
    type: sunrise
  - platform: sun
    name: Next Sunset
    type: sunset

# needed for sun automation
time:
  - platform: homeassistant
    on_time:
      - hours: 7
        minutes: 30
        seconds: 0
        then:
          - logger.log: "Preparing to open."
          - if:
              condition:
                binary_sensor.is_off: door_open_sensor
              then:
                - logger.log: "Opening"
                - cover.open: coop_door
              else:
                - logger.log: "Already open."

# Example configuration entry
switch:
  - platform: restart
    name: "Kippenhok Restart"

sensor:
  - platform: uptime
    name: "Uptime coop_door"
  - platform: wifi_signal
    name: "coop door wifi signal"
    update_interval: 60s
  - platform: dht
    pin: GPIO13
    temperature:
      name: "Temperatuur Kippenhok"
    humidity:
      name: "Vochtigheid Kippenhok"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: D0
    name: upper_sensor
    id: upper_sensor
  - platform: gpio
    pin: D5
    name: lower_sensor
    id: lower_sensor

    # virtual open endstop sensor, triggers when both sensors are high
  - platform: template
    name: "Door open endstop"
    id: door_open_sensor
    lambda: |-
      if ((id(upper_sensor).state + id(lower_sensor).state) == 2){
        return true;
      } else {
        return false;
      }
    on_press:
      then:
        - cover.stop: coop_door

    # virtual closed endstop sensor, triggers when both sensors are low
  - platform: template
    name: "Door closed endstop"
    id: door_closed_sensor
    lambda: |-
      if ((id(upper_sensor).state + id(lower_sensor).state) == 0){
        return true;
      } else {
        return false;
      }
    on_press:
      then:
        - cover.stop: coop_door

output:
  - platform: gpio
    pin: D1
    id: gpio_d1
  - platform: gpio
    pin: D2
    id: gpio_d2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

status_led:
  pin:
    number: 2
    inverted: True

#-----------main cover code---------------
cover:
  - platform: template
    name: "kippenhok deur"
    id: coop_door
    device_class: door
    #assumed_state: true

    lambda: |-
      switch (id(upper_sensor).state + id(lower_sensor).state) {
        case 0: return COVER_CLOSED;
        case 2: return COVER_OPEN;
        case 1: return COVER_CLOSED;
      }
    open_action:
      - output.turn_on: gpio_d1
      - output.turn_off: gpio_d2
      - delay: 8s
      - output.turn_off: gpio_d1
      - output.turn_off: gpio_d2
    close_action:
      - output.turn_off: gpio_d1
      - output.turn_on: gpio_d2
      - delay: 5s
      - output.turn_off: gpio_d1
      - output.turn_off: gpio_d2
    stop_action:
      - output.turn_off: gpio_d1
      - output.turn_off: gpio_d2
