esphome:
  name: scale
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

status_led:
  pin: 
    number: 2
    inverted: True


sensor:
  - platform: hx711
    name: "load_cell"
    dout_pin: 16
    clk_pin: 14
    gain: 128
    update_interval: 20s
    accuracy_decimals: 2
    filters:
      - calibrate_linear:
        - 180000 -> 0
        - 557700 -> 1.76
    unit_of_measurement: kg
  - platform: wifi_signal
    name: "scale_node wifi signal"
    update_interval: 60s
