# Sonoff POW R2 energy meter
esphome:
  name: sonoff_pow
  platform: ESP8266
  board: esp01_1m



wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant

# blue led
status_led:
  pin:
    number: GPIO13
    inverted: True

binary_sensor:
  # sonoff button
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff POW Button"
    internal: true
    on_press:
      - switch.toggle: relay

sensor:
  - platform: cse7766
    current:
      name: "Sonoff Pow R2 Current"
    voltage:
      name: "Sonoff Pow R2 Voltage"
    power:
      name: "Sonoff Pow R2 Power"
      id: power
  - platform: total_daily_energy
    name: "Sonoff POW R2 Total Daily Energy"
    power_id: power
    filters:
        # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    accuracy_decimals: 2

switch:
  - platform: gpio
    id: relay
    pin: GPIO12
    name: "Sonoff POW Relay"
    restore_mode: ALWAYS_ON
