esphome:
  name: test_board_d1_mini
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass



# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "WiFi Signal test_board"
    update_interval: 10s
  - platform: uptime
    name: "Uptime test_board"