esphome:
  name: vijver_boom 
  platform: ESP8266
  board: esp01_1m 
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

status_led:
  pin: 
    number: GPIO13
    inverted: True

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay
  - platform: restart
    name: "vijver boom restart"


dallas:
  - pin: GPIO9
  
sensor:
  - platform: dallas
    address: 0x0C0000001036A228
    name: "VijverT"

  